### ISSUE TITLE
GLSL Compilation failed

### ISSUE THREAD

**Issue by rendoir** [SebLague/Portals#1]
**Error description:** When importing the project, Unity throws an error regarding a failure in compiling the Portal shader.

![Shader compilation error](https://user-images.githubusercontent.com/19244217/75612746-5e739100-5b1e-11ea-90f6-1afe6546f8e9.png)

**Source of the problem:** This is happening because there is a variable called **active** in the Portal.shader while the [GLSL Specification for OpenGL 4.60](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.60.pdf) considers the keyword **active** to be "reserved for future use" and warns that "using them will result in a compile-time
error".

**Possible solution:** The simplest solution is to change the name of the variable **active** to, for example, **displayMask**.

**Software details:** I'm using Ubuntu 18.04 with NVIDIA proprietary 435 drivers. I tested in Unity 2019.3.2f1 being run on OpenGL.

**Comment by SebLague** [comment]
I accepted your pull request, thanks!
